{
    "status": "success",
    "country": "United States",
    "countryCode": "US",
    "region": "KS",
    "regionName": "Kansas",
    "city": "Kansas City",
    "zip": "66117",
    "lat": 39.1141,
    "lon": -94.6275,
    "timezone": "America/Chicago",
    "isp": "ABC Supply Co.",
    "org": "ABC Supply Co",
    "as": "AS22344 ABC Supply Co.",
    "query": "74.112.98.5"
}